import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const root = resolve(import.meta.dir, "../integrations/contremaitre");
const files: Record<string, string> = {};
function walk(dir: string) {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) walk(path);
    else files[relative(root, path)] = readFileSync(path, "utf8");
  }
}
walk(root);
const output = `// Generated by scripts/package-agents.ts from integrations/contremaitre.\nexport const agentAssets: Record<string, string> = ${JSON.stringify(files, null, 2)};\n`;
const target = resolve(import.meta.dir, "../apps/cli/src/agent-assets.ts");
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output)
    throw Error("Agent assets are stale; run bun scripts/package-agents.ts");
} else writeFileSync(target, output);
